import "./globals.css";
import Layout from "@/components/layout/Layout";
import Providers from "@/redux/Providers";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="fa" dir="rtl">
        <body className="font-estedad bg-slate-200 ">
        <Providers>
                <Layout>
                    {children}
                </Layout>
        </Providers>
        </body>
        </html>
    );
}
