import "./globals.css";
import Providers from "@/redux/Providers";
import LayoutWrapper from "@/components/client/layout/LayoutWrapper";

export const metadata = {
    title: "فروشگاه لباس",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {


    return (
        <html lang="fa" dir="rtl">
        <body className="font-estedad bg-white dark:bg-gray-800">
        <Providers>
            <LayoutWrapper>{children}</LayoutWrapper>
        </Providers>
        </body>
        </html>
    );
}
