const users = [
    { id: 1, name: "علی", image: "/Ellipse 18.png" },
    { id: 2, name: "رضا", image: "/Ellipse 19.png" },
    { id: 3, name: "سارا", image: "/Ellipse 20.png" },
    { id: 4, name: "مینا", image: "/Ellipse 21.png" },
    { id: 5, name: "امید", image: "/Ellipse 22.png" },
    { id: 6, name: "حسن", image: "/Ellipse 23.png" },
    { id: 7, name: "زهرا", image: "/Ellipse 24.png" },
    { id: 8, name: "سعید", image: "/Ellipse 26.png" },
    { id: 9, name: "نیما", image: "/Ellipse 18.png" },
    { id: 10, name: "الهام", image: "/Ellipse 18.png" },
    { id: 11, name: "پریسا", image: "/Ellipse 18.png" },
    { id: 12, name: "محمد", image: "/Ellipse 18.png" },
    { id: 13, name: "مهدی", image: "/Ellipse 18.png" },
    { id: 14, name: "فریبا", image: "/Ellipse 18.png" },
    { id: 15, name: "تارا", image: "/Ellipse 18.png" },
    { id: 16, name: "سمیرا", image: "/Ellipse 18.png" },
    { id: 17, name: "حمید", image: "/Ellipse 18.png" },
    { id: 18, name: "نسرین", image: "/Ellipse 18.png" },
];
export {users}